<?php

namespace Knp\IpsumBundle\Document\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ThingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThingRepository extends DocumentRepository
{
}