imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

doctrine:
    dbal:
        dbname:   ipsum_dev

doctrine_mongodb:
    default_database: ipsum_dev

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true
