imports:
    - { resource: security.yml }

framework:
    secret:          betterPuttingThisInTheLocalConfigFile
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    session:
        auto_start:     true
    translator: ~
    default_locale: en

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        closure:
            # We will use Google web API here.
            # You could also download your own jar
            # jar: %kernel.root_dir%/java/compiler.jar
            jar: false
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     localhost
        dbname:   ipsum_prod
        user:     root
        password: ~
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: false

doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
    default_database: ipsum_prod
    document_managers:
        default:
            auto_mapping: true
            mappings:
                StofDoctrineExtensionsBundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: smtp

# JMS Security Extra Simplest Configuration
jms_security_extra: ~

knp_menu:
    twig: true
    default_renderer: twig

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true

fos_user:
    db_driver: orm
    firewall_name: fos_user
    user_class: Knp\IpsumBundle\Entity\User

liip_imagine:
    filter_sets:
        thumbnail:
            filters:
                thumbnail: { size: [300, 300], mode: outbound }
        little_nice_thumbnail:
            filters:
                thumbnail: { size: [150, 150], mode: outbound }

knp_paginator: ~