security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Knp\IpsumBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        fos_user:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/secured/login$
            security: false

        secured_area:
            pattern:    ^/secured/
            provider:   in_memory
            form_login:
                check_path: /secured/login_check
                login_path: /secured/login
            logout:
                path:   /secured/logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Ipsum Area"

        fos_user:
            pattern:    ^/fos-user/
            provider:   fos_user
            form_login:
                check_path: /fos-user/login_check
                login_path: /fos-user/login
            logout:
                path:   /fos-user/logout
                target: /
            anonymous: ~

    access_control:
        - { path: /secured/admin, roles: ROLE_ADMIN }
        - { path: ^/fos-user/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fos-user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fos-user$, roles: Is_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fos-user/, roles: ROLE_USER }
